u1 = User.create(:name=>"James", :email=>"james@james.com", :password=>"poker")
u2 = User.create(:name=>"Dani", :email=>"dani@dani.com",:password=>"poker")


t = Tournament.create(:name=>"Main Event", :buy_in=>10000, :date=> DateTime.new(2012,12, 4))
t1 = Tournament.create(:name=>"5k 6max", :buy_in=>5000, :date=> DateTime.new(2012,12, 7))
t2 = Tournament.create(:name=>"2.5k HA", :buy_in=>2500, :date=> DateTime.new(2012,12, 9))
t3 = Tournament.create(:name=>"Seniors", :buy_in =>1500, :date=> DateTime.new(2012,12, 11))
t4 = Tournament.create(:name=>"Nightly 100", :buy_in=>100, :date=> DateTime.new(2012,12, 13))
t5 = Tournament.create(:name=>"Satellite", :buy_in =>500, :date=> DateTime.new(2012,12, 16))
t6 = Tournament.create(:name=>"2500 6max", :buy_in=>2500, :date=> DateTime.new(2012,12, 19))
t7 = Tournament.create(:name=>"4max", :buy_in=>5000, :date=> DateTime.new(2012,12, 23))
t8 = Tournament.create(:name=>"1k Turbo", :buy_in=>1000, :date=> DateTime.new(2012,12, 28))

p = Prize.create(:user=>u1, :tournament=>t, :amount=> 35000)
p1 = Prize.create(:user=>u2, :tournament=>t1, :amount=>125000)

r = Swap.create(:tournament => t, :receiver=> u2, :percent=>5, :active=>false, :receiver_prize=>p, :status=> 1, :user_prize=> Prize.new(:amount=>0))
r1 = Swap.create(:tournament => t1, :receiver=> u2, :percent=>5, :active=>false, :user_prize=>p, :status=>1, :receiver_prize=> Prize.new(:amount=>0))
r2 = Swap.create(:tournament =>t2, :receiver=> u2, :percent=>7, :active=>true, :status => 0, :user_prize=> Prize.new(:amount=>0), :receiver_prize=> Prize.new(:amount=>0))
r3 = Swap.create(:tournament =>t, :receiver=> u2, :percent=>3, :active=>true, :status => 0, :user_prize=> Prize.new(:amount=>0), :receiver_prize=> Prize.new(:amount=>0))
r4 = Swap.create(:tournament =>t1, :receiver=> u1, :percent=>10, :active=>true, :status => 0, :user_prize=> Prize.new(:amount=>0), :receiver_prize=> Prize.new(:amount=>0))
# # r5 = Lastlonger.create(:tournament =>t, :receiver=> u2, :active=>true)
# # r6 = Lastlonger.create(:tournament =>t, :receiver=> u2, :active=>true)
r7 = Piece.create(:tournament =>t, :receiver => u2, :percent=>10, :active=>true, :status => 0, :user_prize=> Prize.new(:amount=>0))
r8 = Piece.create(:tournament =>t, :receiver => u1, :percent=>25, :active=>true, :status => 0, :user_prize=> Prize.new(:amount=>0))
