require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LastlongersController do

  # This should return the minimal set of attributes required to create a valid
  # Lastlonger. As you add validations to Lastlonger, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LastlongersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all lastlongers as @lastlongers" do
      lastlonger = Lastlonger.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lastlongers).should eq([lastlonger])
    end
  end

  describe "GET show" do
    it "assigns the requested lastlonger as @lastlonger" do
      lastlonger = Lastlonger.create! valid_attributes
      get :show, {:id => lastlonger.to_param}, valid_session
      assigns(:lastlonger).should eq(lastlonger)
    end
  end

  describe "GET new" do
    it "assigns a new lastlonger as @lastlonger" do
      get :new, {}, valid_session
      assigns(:lastlonger).should be_a_new(Lastlonger)
    end
  end

  describe "GET edit" do
    it "assigns the requested lastlonger as @lastlonger" do
      lastlonger = Lastlonger.create! valid_attributes
      get :edit, {:id => lastlonger.to_param}, valid_session
      assigns(:lastlonger).should eq(lastlonger)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lastlonger" do
        expect {
          post :create, {:lastlonger => valid_attributes}, valid_session
        }.to change(Lastlonger, :count).by(1)
      end

      it "assigns a newly created lastlonger as @lastlonger" do
        post :create, {:lastlonger => valid_attributes}, valid_session
        assigns(:lastlonger).should be_a(Lastlonger)
        assigns(:lastlonger).should be_persisted
      end

      it "redirects to the created lastlonger" do
        post :create, {:lastlonger => valid_attributes}, valid_session
        response.should redirect_to(Lastlonger.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lastlonger as @lastlonger" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lastlonger.any_instance.stub(:save).and_return(false)
        post :create, {:lastlonger => {  }}, valid_session
        assigns(:lastlonger).should be_a_new(Lastlonger)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lastlonger.any_instance.stub(:save).and_return(false)
        post :create, {:lastlonger => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lastlonger" do
        lastlonger = Lastlonger.create! valid_attributes
        # Assuming there are no other lastlongers in the database, this
        # specifies that the Lastlonger created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lastlonger.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => lastlonger.to_param, :lastlonger => { "these" => "params" }}, valid_session
      end

      it "assigns the requested lastlonger as @lastlonger" do
        lastlonger = Lastlonger.create! valid_attributes
        put :update, {:id => lastlonger.to_param, :lastlonger => valid_attributes}, valid_session
        assigns(:lastlonger).should eq(lastlonger)
      end

      it "redirects to the lastlonger" do
        lastlonger = Lastlonger.create! valid_attributes
        put :update, {:id => lastlonger.to_param, :lastlonger => valid_attributes}, valid_session
        response.should redirect_to(lastlonger)
      end
    end

    describe "with invalid params" do
      it "assigns the lastlonger as @lastlonger" do
        lastlonger = Lastlonger.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lastlonger.any_instance.stub(:save).and_return(false)
        put :update, {:id => lastlonger.to_param, :lastlonger => {  }}, valid_session
        assigns(:lastlonger).should eq(lastlonger)
      end

      it "re-renders the 'edit' template" do
        lastlonger = Lastlonger.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lastlonger.any_instance.stub(:save).and_return(false)
        put :update, {:id => lastlonger.to_param, :lastlonger => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lastlonger" do
      lastlonger = Lastlonger.create! valid_attributes
      expect {
        delete :destroy, {:id => lastlonger.to_param}, valid_session
      }.to change(Lastlonger, :count).by(-1)
    end

    it "redirects to the lastlongers list" do
      lastlonger = Lastlonger.create! valid_attributes
      delete :destroy, {:id => lastlonger.to_param}, valid_session
      response.should redirect_to(lastlongers_url)
    end
  end

end
